name: Günah Arındırıcı
description: Namaz alarmı ve kontrol uygulaması

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.2.3
  android_alarm_manager_plus: ^3.0.0
  geolocator: ^12.0.0
  http: ^1.2.2
  camera: ^0.11.0
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.0
  audioplayers: ^6.1.0

flutter:
  uses-material-design: true